### ISSUE TITLE
USER STORY 3C: Add Images

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#11]
As a **site user**, I can **attached images to a travel log** so that I can **add extra value and information to each log**.

**Tasks:**
- [x] Implement functionality that allows a user to add several images to a specific travel log entry.
- [x] Implement user-friendly UX and UI.

**Acceptance Criteria:**
- [x] User is able to add images to a log entry.
- [x] UX and UI is intuitive and user-friendly.
