### ISSUE TITLE
USER STORY 3D: Delete images

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#12]
As a **site user**, I can **delete images** so that **I can remove information from the site**.

**Tasks:**
- [x] Add functionality so a user can delete individual images from a log entry.
- [x] Implement user-friendly UX and UI.

**Acceptance Criteria:**
- [x] User is able to delete image from a log entry.
- [x] UX and UI is intuitive.
