### ISSUE TITLE
USER STORY: Site pagination

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#15]
As a **site user**, I can **access different pages on the site** so that **I can navigate smoothly through all the functionality of the site**.

**Task:**

- [x] Set up distinct pages for different functionalities of the site.

**Acceptance Criteria:**

- [x] Pages are displaying with intended functionality.
- [x] Pages are designed with optimal UX in mind.
