### ISSUE TITLE
USER STORY 1A: Navigation Menu

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#17]
As a **user**, I can **see a navigation menu** so that **I can easily navigate the site**.

**Tasks:**
- [x] Implement navigation responsive navigation bar in header of site.
- [x] Implement intuitive UX design.

**Acceptance Criteria:**
- [x] Navbar content works as intended and is intuitive
- [x] Design of navbar is clean and responsive.
