### ISSUE TITLE
USER STORY 4A: See Publicly Available Entries Listed

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#20]
As a **user**, I can **view log entries** so that **I can browse the site content and get an impression of its purpose**.

**Tasks:**
- [x] Implement a view and template to display log entries in list form.
- [x] Implement pleasing UX and UI

**Acceptance Criteria:**
- [x] Log entries can be viewed easily on the home page of the site.
- [x] The interphase is visually pleasing and easy to use.
