### ISSUE TITLE
USER STORY 4B: Log Entry Detail View

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#21]
As a **user**, I can **view the details of each log entry** so that **I can learn in depth content about each trip**.

**Tasks:**
- [x] Implement a view and template to display the details of each log entry including an image gallery.
- [x] Implement pleasing UX and UI

**Acceptance Criteria:**
- [x] Log entry details can be viewed easily by clicking on the summary card displayed on the home page.
- [x] The interphase is visually pleasing and easy to use.
