### ISSUE TITLE
USER STORY 4C: View Log Entries sorted by Country Category

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#22]
As a **user**, I can **view log entries sorted by country** so that **I can narrow my search and focus on a particular region of personal interest**.

**Tasks:**
- [x] Implement a view and template to display log entries for a specific country category in list form.
- [x] Implement a drop down menu in the navbar that allows quick access to the country selection.
- [x] Implement pleasing UX and UI

**Acceptance Criteria:**
- [x] Log entries can be viewed easily on a specific country category page.
- [x] Dropdown menu is working as intended.
- [x] The interphase is visually pleasing and easy to use.
