### ISSUE TITLE
USER STORY 4D: Personal Entry View

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#23]
As a **user**, I can **view my personal log entries on a separate page** so that **I can view my own content concisely and access it for the purpose of editing**.

**Tasks:**
- [x] Implement a view and template to display the log entries owned by an authenticated user in list form.
- [x] Add display of draft/published status and privacy setting.
- [x] Implement pleasing UX and UI

**Acceptance Criteria:**
- [x] The users log entries can be viewed easily on a separate page of the site.
- [x] Status and privacy settings are displayed.
- [x] The interphase is visually pleasing and easy to use.
