### ISSUE TITLE
USER STORY: View travel log list

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#5]
As a **site user**, I can **view a list of travel logs** so that **browse and read featured content**.

**Task:**

- [x] Display submitted logs as a list on the site.

**Acceptance Criteria**

- [x] List of travel logs is displayed.
- [x] Navigation is easy and UX is appealing.
