### ISSUE TITLE
USER STORY: Delete a user account

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#6]
As a **site user**, I can **delete my account**, so that **my personal information is removed from the site**.

**Tasks:**
- [ ] Set up functionality to delete a user account.
- [ ] Implement user-friendly UX and UI.

**Acceptance Criteria:**
- [ ] User is able to delete and account.
- [ ] UX and UI is user-friedly.
