### ISSUE TITLE
USER STORY 3A: Add a trip log

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#7]
As a **site user**, I can **add a trip log** so that **I can store trip information online**.

**Task**
- [x] Add a log entry from admin panel
- [x] Create a form to submit a log entry for non-admin users
- [x] Implement styling 

**Acceptance Criteria**
- [x] Admin user can add a log entry
- [x] Non-admin user can add a log entry from a form template
- [x] Styling and UX/UI is appealing and consistent
