### ISSUE TITLE
USER STORY 3B: Edit and delete a trip log

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#8]
As a **site user**, I can **access my trip logs** so that **I can edit or delete my log entries**.

**Tasks:**
- [x] Add editing and delete functionality to a log entry for a registered user.
- [x] Implement user-friendly UX and UI.

**Acceptance Criteria:**
- [x] User is able to edit or delete a log entry.
- [x] UX and UI is intuitive and user-friendly.
