### ISSUE TITLE
USER STORY: Delete a log entry

### ISSUE THREAD

**Issue by URiem** [URiem/worldtravellog#9]
As a **site user**, I can **delete a trip log**, so that **the information is removed from the site**.

**Tasks:**
- [ ] Implement delete functionality for a log entry.
- [ ] Implement user-friendly UX and UI.

**Acceptance Criteria:**
- [ ] A user is able to delete a log entry.
- [ ] UX and UI is user-friendly.
